pull_request_rules:
  - name: automatic backport of common pages
    conditions:
      - base=rolling
      - "files~=Governance|Contact|index|Marketing|ROSCon-Content|Roadmap|Releases|Feature-Ideas"
    actions:
      backport:
        branches:
          - humble

  - name: backport at reviewers discretion
    conditions:
      - base=rolling
      - "label=backport-all"
    actions:
      backport:
        branches:
          - humble

  - name: backport to humble at reviewers discretion
    conditions:
      - base=rolling
      - "label=backport-humble"
    actions:
      backport:
        branches:
          - humble
