pull_request_rules:
  - name: automatic backport of common pages
    conditions:
      - base=rolling
      - "files~=Governance|Contact|index|Marketing|ROSCon-Content|Roadmap|Releases|Feature-Ideas|Metrics"
    actions:
      backport:
        branches:
<<<<<<< HEAD
=======
          - lyrical
          - kilted 
>>>>>>> f696450 (Add support for ROS Lyrical (#6484))
          - jazzy
          - humble

  - name: backport at reviewers discretion
    conditions:
      - base=rolling
      - "label=backport-all"
    actions:
      backport:
        branches:
<<<<<<< HEAD
          - jazzy
          - humble

=======
          - lyrical
          - kilted
          - jazzy
          - humble

  - name: backport to lyrical at reviewers discretion
    conditions:
      - base=rolling
      - "label=backport-lyrical"
    actions:
      backport:
        branches:
          - lyrical

  - name: backport to kilted at reviewers discretion
    conditions:
      - base=rolling
      - "label=backport-kilted"
    actions:
      backport:
        branches:
          - kilted

>>>>>>> f696450 (Add support for ROS Lyrical (#6484))
  - name: backport to jazzy at reviewers discretion
    conditions:
      - base=rolling
      - "label=backport-jazzy"
    actions:
      backport:
        branches:
          - jazzy

  - name: backport to humble at reviewers discretion
    conditions:
      - base=rolling
      - "label=backport-humble"
    actions:
      backport:
        branches:
          - humble
